export const COURSE_CATALOG = [
  { level: '100', semester: 'Harmattan', courseCode: 'MTH 101', courseTitle: 'Elementary Mathematics I', units: 4 },
  { level: '100', semester: 'Harmattan', courseCode: 'PHY 101', courseTitle: 'General Physics I (Theory)', units: 3 },
  { level: '100', semester: 'Harmattan', courseCode: 'PHY 107', courseTitle: 'General Physics I (Practical)', units: 1 },
  { level: '100', semester: 'Harmattan', courseCode: 'CHM 101', courseTitle: 'General Chemistry I (Theory)', units: 3 },
  { level: '100', semester: 'Harmattan', courseCode: 'CHM 107', courseTitle: 'General Chemistry I (Practical)', units: 1 },
  { level: '100', semester: 'Harmattan', courseCode: 'BIO 101', courseTitle: 'General Biology I (Theory)', units: 2 },
  { level: '100', semester: 'Harmattan', courseCode: 'BIO 107', courseTitle: 'General Biology I (Practical)', units: 1 },
  { level: '100', semester: 'Harmattan', courseCode: 'ENG 101', courseTitle: 'Workshop Practice I', units: 1 },
  { level: '100', semester: 'Harmattan', courseCode: 'ENG 103', courseTitle: 'Engineering Drawing I', units: 1 },
  { level: '100', semester: 'Harmattan', courseCode: 'GST 101', courseTitle: 'Use of English I', units: 2 },
  { level: '100', semester: 'Harmattan', courseCode: 'GST 103', courseTitle: 'Humanities', units: 1 },
  { level: '100', semester: 'Harmattan', courseCode: 'IGB 101', courseTitle: 'Introduction to Igbo Grammar, Composition and Comprehension', units: 1, electiveGroup: '100-harmattan-language' },
  { level: '100', semester: 'Harmattan', courseCode: 'FRN 101', courseTitle: 'French Language I', units: 1, electiveGroup: '100-harmattan-language' },
  { level: '100', semester: 'Rain', courseCode: 'MTH 102', courseTitle: 'Elementary Mathematics II', units: 4 },
  { level: '100', semester: 'Rain', courseCode: 'PHY 102', courseTitle: 'General Physics II (Theory)', units: 3 },
  { level: '100', semester: 'Rain', courseCode: 'PHY 108', courseTitle: 'General Physics II (Practical)', units: 1 },
  { level: '100', semester: 'Rain', courseCode: 'CHM 102', courseTitle: 'General Chemistry II (Theory)', units: 3 },
  { level: '100', semester: 'Rain', courseCode: 'CHM 108', courseTitle: 'General Chemistry II (Practical)', units: 1 },
  { level: '100', semester: 'Rain', courseCode: 'ENG 102', courseTitle: 'Workshop Practice II', units: 1 },
  { level: '100', semester: 'Rain', courseCode: 'ENG 104', courseTitle: 'Engineering Drawing II', units: 1 },
  { level: '100', semester: 'Rain', courseCode: 'GST 102', courseTitle: 'Use of English II', units: 2 },
  { level: '100', semester: 'Rain', courseCode: 'GST 108', courseTitle: 'Social Sciences I', units: 2 },
  { level: '100', semester: 'Rain', courseCode: 'GST 110', courseTitle: 'Science, Technology and Society', units: 1 },
  { level: '100', semester: 'Rain', courseCode: 'IGB 102', courseTitle: 'Introduction to Igbo Culture', units: 1, electiveGroup: '100-rain-language' },
  { level: '100', semester: 'Rain', courseCode: 'FRN 102', courseTitle: 'French Language II', units: 1, electiveGroup: '100-rain-language' },
  { level: '200', semester: 'Harmattan', courseCode: 'IFT 201', courseTitle: 'Introduction to Information Technology', units: 2 },
  { level: '200', semester: 'Harmattan', courseCode: 'IFT 203', courseTitle: 'Data Structures & Algorithms', units: 3 },
  { level: '200', semester: 'Harmattan', courseCode: 'CSC 201', courseTitle: 'Computers and Applications I', units: 4 },
  { level: '200', semester: 'Harmattan', courseCode: 'MTH 201', courseTitle: 'Mathematical Methods I', units: 3 },
  { level: '200', semester: 'Harmattan', courseCode: 'ENG 201', courseTitle: 'Workshop Practice III', units: 1 },
  { level: '200', semester: 'Harmattan', courseCode: 'GST 201', courseTitle: 'Social Sciences II', units: 1 },
  { level: '200', semester: 'Harmattan', courseCode: 'ECN 201', courseTitle: 'Economics I', units: 3 },
  { level: '200', semester: 'Harmattan', courseCode: 'STA 211', courseTitle: 'Introduction to Statistics & Probability', units: 3 },
  { level: '200', semester: 'Rain', courseCode: 'CIT 202', courseTitle: 'Computer Programming I', units: 3 },
  { level: '200', semester: 'Rain', courseCode: 'IFT 204', courseTitle: 'Human-Computer Interaction', units: 2 },
  { level: '200', semester: 'Rain', courseCode: 'IFT 206', courseTitle: 'Digital Logic Circuits and Design', units: 2 },
  { level: '200', semester: 'Rain', courseCode: 'IFT 208', courseTitle: 'Discrete Structures', units: 2 },
  { level: '200', semester: 'Rain', courseCode: 'CIT 204', courseTitle: 'Computer Organization and Architecture I', units: 2 },
  { level: '200', semester: 'Rain', courseCode: 'MTH 202', courseTitle: 'Mathematical Methods II', units: 3 },
  { level: '200', semester: 'Rain', courseCode: 'MGT 206', courseTitle: 'Industrial Psychology', units: 3 },
  { level: '200', semester: 'Rain', courseCode: 'ENG 226', courseTitle: 'Introduction to Electrical/Electronic Engineering', units: 3 },
  { level: '200', semester: 'Rain', courseCode: 'SIW 200', courseTitle: 'Students Industrial Work Experience', units: 2 },
  { level: '300', semester: 'Harmattan', courseCode: 'IFT 301', courseTitle: 'Principles of Telecommunication Technology', units: 2 },
  { level: '300', semester: 'Harmattan', courseCode: 'IFT 303', courseTitle: 'Data Communication and Networking', units: 3 },
  { level: '300', semester: 'Harmattan', courseCode: 'IFT 305', courseTitle: 'Multimedia Application Systems and Development', units: 3 },
  { level: '300', semester: 'Harmattan', courseCode: 'IFT 307', courseTitle: 'Operations Research', units: 2 },
  { level: '300', semester: 'Harmattan', courseCode: 'CIT 301', courseTitle: 'Operating System I', units: 2 },
  { level: '300', semester: 'Harmattan', courseCode: 'CIT 303', courseTitle: 'Systems Analysis and Design', units: 3 },
  { level: '300', semester: 'Harmattan', courseCode: 'CIT 305', courseTitle: 'Introduction to Software Engineering', units: 3 },
  { level: '300', semester: 'Harmattan', courseCode: 'ENS 301', courseTitle: 'Introduction to Entrepreneurship & Innovation', units: 2 },
  { level: '300', semester: 'Rain', courseCode: 'IFT 302', courseTitle: 'Information and Network Security', units: 3 },
  { level: '300', semester: 'Rain', courseCode: 'IFT 304', courseTitle: 'Computer Graphics', units: 2 },
  { level: '300', semester: 'Rain', courseCode: 'IFT 306', courseTitle: 'Management Information Systems', units: 2 },
  { level: '300', semester: 'Rain', courseCode: 'IFT 308', courseTitle: 'Information Technology in Business', units: 2 },
  { level: '300', semester: 'Rain', courseCode: 'CIT 302', courseTitle: 'Computer Programming II', units: 3 },
  { level: '300', semester: 'Rain', courseCode: 'CIT 304', courseTitle: 'Database Management System I', units: 3 },
  { level: '300', semester: 'Rain', courseCode: 'CIT 306', courseTitle: 'Web Design and Programming I', units: 3 },
  { level: '300', semester: 'Rain', courseCode: 'ENS 302', courseTitle: 'Business Creation Growth & Corporate Governance', units: 2 },
  { level: '400', semester: 'Harmattan', courseCode: 'IFT 401', courseTitle: 'Internet of Things (IoT)', units: 3 },
  { level: '400', semester: 'Harmattan', courseCode: 'IFT 403', courseTitle: 'Technical Report Writing in Information Technology', units: 2 },
  { level: '400', semester: 'Harmattan', courseCode: 'IFT 405', courseTitle: 'Research Methodology & Capstone Management', units: 2 },
  { level: '400', semester: 'Harmattan', courseCode: 'IFT 407', courseTitle: 'Remote Sensing Technology', units: 3 },
  { level: '400', semester: 'Harmattan', courseCode: 'IFT 409', courseTitle: 'Data Science', units: 3 },
  { level: '400', semester: 'Harmattan', courseCode: 'CIT 401', courseTitle: 'Database Management Systems II', units: 3 },
  { level: '400', semester: 'Harmattan', courseCode: 'CIT 403', courseTitle: 'Web Design and Programming II', units: 3 },
  { level: '400', semester: 'Rain', courseCode: 'SIW 400', courseTitle: 'Students Industrial Work Experience', units: 4 },
  { level: '400', semester: 'Rain', courseCode: 'SIW 401', courseTitle: 'Industrial Attachment (Long Vacation)', units: 2 },
  { level: '500', semester: 'Harmattan', courseCode: 'IFT 501', courseTitle: 'Cyber Security and Networks', units: 2 },
  { level: '500', semester: 'Harmattan', courseCode: 'IFT 503', courseTitle: 'Embedded Systems and Pervasive Computing', units: 2 },
  { level: '500', semester: 'Harmattan', courseCode: 'IFT 505', courseTitle: 'Web Server Technologies and Administration', units: 3 },
  { level: '500', semester: 'Harmattan', courseCode: 'IFT 507', courseTitle: 'Software Engineering and Practice', units: 3 },
  { level: '500', semester: 'Harmattan', courseCode: 'IFT 509', courseTitle: 'IT Project Management', units: 2 },
  { level: '500', semester: 'Harmattan', courseCode: 'IFT 511', courseTitle: 'Mobile Application Development', units: 2 },
  { level: '500', semester: 'Harmattan', courseCode: 'IFT 513', courseTitle: 'Block-Chain Technology', units: 2 },
  { level: '500', semester: 'Rain', courseCode: 'IFT 502', courseTitle: 'Computer Modelling & Simulation', units: 3 },
  { level: '500', semester: 'Rain', courseCode: 'IFT 504', courseTitle: 'Social Issues and Professional Ethics in Information Technology', units: 2 },
  { level: '500', semester: 'Rain', courseCode: 'IFT 506', courseTitle: 'Special Topics in Information Technology (Seminar)', units: 1 },
  { level: '500', semester: 'Rain', courseCode: 'IFT 508', courseTitle: 'Systems Implementation & Evaluation', units: 2 },
  { level: '500', semester: 'Rain', courseCode: 'IFT 510', courseTitle: 'Network Administration and Management', units: 3 },
  { level: '500', semester: 'Rain', courseCode: 'IFT 512', courseTitle: 'Intelligent Systems', units: 3 },
  { level: '500', semester: 'Rain', courseCode: 'IFT 514', courseTitle: 'Information Assurance & Security', units: 2 }
];
